style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/elioseverojunior/semtag
options:
  commits:
    filters:
      Type:
        - bugfix
        - chore
        - feat
        - feature
        - fix
        - hotfix
        - init
        - perf
        - refactor
        - sec
        - security
        - support
  commit_groups:
    title_maps:
      bugfix: Bug Fixes
      chore: Chores
      feat: Features
      feature: Features
      fix: Bug Fixes
      hotfix: Hot Fixes
      init: Repository Initialization
      perf: Performance Improvements
      refactor: Code Refactoring
      sec: Security
      security: Security
      support: Support
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
